spring.application.name: greetings
server.port: 9000
logging.level.org.springframework.security: DEBUG
security.user.password: password
security:
  oauth2:
    resource:
      userInfoUri: https://api.github.com/user